// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {collector} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetMetrics():Promise<collector.Metrics>;

export function SaveConfig(arg1:config.Config):Promise<void>;
